name: Deploy to EECS Vhosts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/w/ignite/"
          EXCLUDE: "/.git/, /.github/"
          SCRIPT_AFTER: |
            chmod -R 755 /w/ignite
            chmod -R 644 /w/ignite/*
            chmod -R 755 /w/ignite/*/. 2>/dev/null || true
